version: '3.8'

services:
  kokoro-gpu:
    image: ghcr.io/remsky/kokoro-fastapi-gpu:latest
    container_name: kokoro-gpu
    restart: always
    ports:
      - "8001:8880"
    volumes:
      - ./api:/app/api
  environment:
        # 显式指定容器可见的 GPU 索引为 0
        - NVIDIA_VISIBLE_DEVICES=0
        - NVIDIA_DRIVER_CAPABILITIES=all
        - DOWNLOAD_MODEL=false
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: ["gpu"]
    tty: true
    stdin_open: true
